### ISSUE TITLE
Can i reload Chart with some updated data?

### ISSUE THREAD

**Issue by AlessandroFronteddu** [ArthurGuibert/FSLineChart#10]
Hi, does FSLineChart support reloading ( using for example NSTimer ) chart with updated data ? 

More in depth: can i reload chart every seconds with new data ?

**Comment by ArthurGuibert** [comment]
Hi! I don't really know... it should be doable as long as you keep the same number of points and then update the path. As it is now I'm not sure the architecture of FSLineChart allows that. But that's definitely something worth digging! I'm going to have a look :)

Alternatively, as a temporary solution, you can remove the chart view and create a new one with the new data.

**Comment by thedp** [comment]
+1

**Comment by AlessandroFronteddu** [comment]
+1

**Comment by ArthurGuibert** [comment]
It should work better now. It doesn't mean this library really supports live data though.
