### ISSUE TITLE
Seems crash when all data are zero

### ISSUE THREAD

**Issue by zenghaojim33** [ArthurGuibert/FSLineChart#18]
NSMutableArray* chartData = [NSMutableArray arrayWithCapacity:10];
    srand(time(nil));
    for(int i=0;i<10;i++) {
        int r = (rand() + rand()) % 1000;
        chartData[i] = [NSNumber numberWithInt:0];
    }
    // Creating the line chart
    FSLineChart* lineChart = [[FSLineChart alloc] initWithFrame:CGRectMake(20, 60, [UIScreen mainScreen].bounds.size.width - 40, 166)];
    lineChart.verticalGridStep = 5;
    lineChart.horizontalGridStep = 9;
    //lineChart.fillColor = nil;
    lineChart.labelForIndex = ^(NSUInteger item) {
        return [NSString stringWithFormat:@"%lu",(unsigned long)item];
    };
    lineChart.labelForValue = ^(CGFloat value) {
        return [NSString stringWithFormat:@"%.f", value];
    };
    [lineChart setChartData:chartData];
    return lineChart;

 I replace all the data point with 0 in the example project and the app crashed. Here is the failure information:

Assertion failed: (CGFloatIsValid(x) && CGFloatIsValid(y)), function void CGPathMoveToPoint(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat), file Paths/CGPath.cc, line 254.

**Comment by mhergon** [comment]
Same issue. Please, any fix?

**Comment by magdics** [comment]
Any idea when this will be fixed?

**Comment by ArthurGuibert** [comment]
I am going to have a look. However I accept pull requests in general. So if you have a fix please submit one and I'll review it :)

**Comment by magdics** [comment]
I don't have a fix, but would very much appreciate one, this is a fantastic chart tool.

**Comment by magdics** [comment]
Any idea on the timeframe for the fix?

**Comment by magdics** [comment]
Any progress on the all zero bug?

**Comment by arnaudWasappli** [comment]
```    CGFloat scale = MAX(0, _axisHeight / (maxBound - minBound)); ```

**Comment by iSemic** [comment]
I fixed this:
CGFloat b = maxBound - minBound;
CGFloat scale = b != 0 ? _axisHeight / b : 0;

**Comment by ArthurGuibert** [comment]
It should be fixed now. Thanks for reporting the issue.
