### ISSUE TITLE
'clearChartData:' doesn't work

### ISSUE THREAD

**Issue by shz2050** [ArthurGuibert/FSLineChart#27]
When I call the method ''clearChartData:', the chart will draw again. 

The method 'drawRect:' will call to redraw.

So I can't clear the chart.

Help me, thanks.

**Comment by StevenWung** [comment]
I met this problem too.
Any solution?

**Comment by shz2050** [comment]
It works for me.   
 [self.chart setChartData:@[@0]];
 [self.chart clearChartData];
