### ISSUE TITLE
months(labelForIndex) can't be two objects?

### ISSUE THREAD

**Issue by sp55** [ArthurGuibert/FSLineChart#30]
- (void)loadChartWithDates {
 
    
    NSArray *chartData=@[@"78",@"23"];
    
    NSArray* months = @[@"2016-05-23", @"2016-05-24"];
    
    // Setting up the line chart
    _chartWithDates.verticalGridStep = 6;
    _chartWithDates.horizontalGridStep = 3;
    _chartWithDates.fillColor = nil;
    _chartWithDates.displayDataPoint = YES;
    _chartWithDates.dataPointColor = [UIColor fsOrange];
    _chartWithDates.dataPointBackgroundColor = [UIColor fsOrange];
    _chartWithDates.dataPointRadius = 2;
    _chartWithDates.color = [_chartWithDates.dataPointColor colorWithAlphaComponent:0.3];
    _chartWithDates.valueLabelPosition = ValueLabelLeftMirrored;
    
    _chartWithDates.labelForIndex = ^(NSUInteger item) {
        return months[item];
    };
    
    _chartWithDates.labelForValue = ^(CGFloat value) {
        return [NSString stringWithFormat:@"%.f", value];
    };
    
    [_chartWithDates setChartData:chartData];
}

if    NSArray *chartData=@[@"78",@"23"];     NSArray* months = @[@"2016-05-23", @"2016-05-24"];
the second object  2016-05-24 can't be load ?
why?

**Comment by ArthurGuibert** [comment]
Is it not displayed? It mostly depends on the horizontalGridStep value.

**Comment by sp55** [comment]
// Setting up the line chart
    if (xArr.count==2) { //judge by parr
        DLog(@"xArr_Count is 2");
        _chartWithDates.verticalGridStep = 2;
        _chartWithDates.horizontalGridStep = 2;
    }
    else{
        DLog(@"xArr_Count--%ld",[xArr count]);
        
        _chartWithDates.verticalGridStep = 6;
        _chartWithDates.horizontalGridStep = 3;
    }


i  find the result   
if  xArr.count ==2   i  should change   horizontalGridStep 




and  thanks for your reply
