### ISSUE TITLE
How to plot multiple lines?

### ISSUE THREAD

**Issue by reyanshh** [ArthurGuibert/FSLineChart#40]

**Comment by ArthurGuibert** [comment]
It's not possible at the moment, at least not with one view.

**Comment by rheyansh** [comment]
Sorry foe the late reply. Just a solution proposed you.
[FSLineChart.zip](https://github.com/ArthurGuibert/FSLineChart/files/691312/FSLineChart.zip)

Usage:

// Generating some dummy data
    NSMutableArray* chartData = [NSMutableArray arrayWithCapacity:7];
    for(int i=0;i<7;i++) {
        chartData[i] = [NSNumber numberWithFloat: (float)i / 30.0f + (float)(rand() % 100) / 500.0f];
    }
    
    NSArray* months = @[@"13:30", @"13:45", @"14:00", @"14:15", @"14:30", @"14:45", @"15:00"];
    
    [self.lineChart setBackgroundColor:[UIColor clearColor]];
    
    // Setting up the line chart
    self.lineChart.verticalGridStep = (int)chartData.count - 1;
    self.lineChart.horizontalGridStep = (int)chartData.count - 1;
    self.lineChart.fillColor = nil;
    self.lineChart.displayDataPoint = NO;
    self.lineChart.dataPointColor = [UIColor clearColor];
    self.lineChart.dataPointBackgroundColor = [UIColor clearColor];
    self.lineChart.indexLabelTextColor = RGBCOLOR(117, 172, 197, 1);
    self.lineChart.axisColor = RGBCOLOR(117, 172, 197, 1);

    self.lineChart.innerGridColor = [UIColor clearColor];
    self.lineChart.lineWidth = 2;
    self.lineChart.axisLineWidth = 1.5;

    self.lineChart.dataPointRadius = 2;
    self.lineChart.color = RGBCOLOR(117, 172, 197, 1);
    self.lineChart.valueLabelPosition = ValueLabelLeftMirrored;
    self.lineChart.dashedLines = NO;
    
    self.lineChart.labelForIndex = ^(NSUInteger item) {
        return months[item];
    };
    
    //    self.lineChart.labelForValue = ^(CGFloat value) {
    //        return [NSString stringWithFormat:@"%.02f €", value];
    //    };
    
    [self.lineChart setChartData:chartData];
    
    NSMutableArray* chartData1 = [NSMutableArray arrayWithCapacity:7];
    for(int i=0;i<7;i++) {
        chartData1[i] = [NSNumber numberWithFloat: (float)i / 30.0f + (float)(rand() % 100) / 300.0f];
    }
    
    self.lineChart.color = RGBCOLOR(183, 209, 221, 1);
    self.lineChart.lineWidth = 1.5;
    self.lineChart.dashedLines = YES;

    [self.lineChart setChartData:chartData1];

**Comment by tomerubin2** [comment]
I would love it if you could add multiple lines in the same chart! 👍
