### ISSUE TITLE
If we have lots of data , the chart can't scroll at all.

### ISSUE THREAD

**Issue by vhikd** [ArthurGuibert/FSLineChart#7]
All data will be pushed together, the labelIndex in particular.

**Comment by ArthurGuibert** [comment]
Yes, FSLineChart doesn't support scrolling. Could be something to be added in the future? I'll definitely accept any pull request in the sense.

**Comment by vhikd** [comment]
I had draw the Y axis in another view , and use the axis view as changeless axis on the top view. And send the chart view to scroll view . In the chart view , the Y axis will not be draw again.

**Comment by vhikd** [comment]
If we have only one point, the chart will be crash.

**Comment by ArthurGuibert** [comment]
The crash is another issue. There is no plan to support scrolling the chart... You can still put the view in a scroll view and adjust the width to the the amount of points you have.
